#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import samba

#
# Check if routes for this new DC must be added automatically
# Symlinked by import-module/52update_routes_symlink
# Symlinked by restore-module/70update_routes_symlink
#

if os.getenv("IPADDRESS") and os.getenv("SERVER_ROLE") != "member":
    samba.push_vpn_routes()
