{
 "title": "Samba Audit statistics",
 "tags": [ "samba" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "samba_audit_database", "label": "Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM samba_audit WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Operation type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operation results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  split_part(result, ' ', 1) AS result,\n  COUNT(*) AS count\nFROM\n  samba_audit\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  result\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "Users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  username AS user,\n  COUNT(*) AS count\nFROM\n  samba_audit\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  username\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "Source addresses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  addr AS address,\n  COUNT(*) AS count\nFROM\n  samba_audit\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  addr\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "Shares",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct share) FROM samba_audit WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(username)) FROM samba_audit WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Most active users",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  username,\n  COUNT(*) AS activity_count\nFROM\n  samba_audit\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  username\nORDER BY\n  activity_count DESC;"
    }
   ]
  },
  {
   "title": "Most active shares",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  share,\n  COUNT(*) AS activity_count\nFROM\n  samba_audit\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  share\nORDER BY\n  activity_count DESC;"
    }
   ]
  },
  {
   "title": "Most active paths",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    substring(path, 13) as path,\n    COUNT(*) AS activity_count\nFROM \n    samba_audit\nWHERE $__timeFilter(time) \nGROUP BY \n    substring(path, 13)\nORDER BY \n    activity_count DESC;\n"
    }
   ]
  },
  {
   "title": "Events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('minute', time) AS minute,\n    COUNT(*) AS count\nFROM \n    samba_audit\nWHERE $__timeFilter(time) \nGROUP BY \n    minute\nORDER BY \n    minute ASC;"
    }
   ]
  },
  {
   "title": "Last 100 events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, share, path, username, op, result FROM samba_audit WHERE $__timeFilter(time) ORDER BY (time) DESC LIMIT 100"
    }
   ]
  }
 ]
}