#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This script updates the api-moduled.env file to include PYTHONPATH
# in the AMLD_EXPORT_ENV variable if it's not already present.
import sys
import agent

file = "api-moduled.env"

# Read the environment file as a dictionary
env_file = agent.read_envfile(file)

amld_export_env = env_file.get("AMLD_EXPORT_ENV", "")
if "PYTHONPATH" in amld_export_env.split():
    sys.exit(0)

# Add PYTHONPATH at the end
python_path = f"{amld_export_env} PYTHONPATH"
env_file["AMLD_EXPORT_ENV"] = python_path

# Write the updated environment back to the file
agent.write_envfile(file, env_file)
print(f"AMLD_EXPORT_ENV updated: {python_path}", file=sys.stderr)
