#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

agent.assert_exp(agent.add_public_service(os.environ['MODULE_ID'], [
    "3702/udp", # wsdd
    "5357/tcp" # wsdd
    ]))
