#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

module_id = os.environ["MODULE_ID"]
rdbw = agent.redis_connect(privileged=True)
rdbw.sadd(f"module/{module_id}/flags", "core_module", "account_provider")
