#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

if ! [[ -f nbalias.txt ]]; then
    exit 0 # skip this step if file server is not migrated
fi

# Transfer the name of NS7 (the Samba file server) to the DC, as an alias.

export NBALIAS
NBALIAS="$(< nbalias.txt)"

echo "Set DC NBALIAS=${NBALIAS,,}:"

sed -i -r "s/^NBALIAS=.*/NBALIAS=${NBALIAS,,}/" environment

podman exec -i --env=NBALIAS samba-dc bash -s <<'EOF'
if [[ -z "${NBALIAS}" ]]; then
    exit 0
fi

# Delete the NS7 computer account:
samba-tool computer delete "${NBALIAS,,}$"

# Clean up stale DNS records:
samba-tool dns cleanup 127.0.0.1 "${NBALIAS,,}.$(hostname -d)" -P

# Add SPNs to the DC computer account
samba-tool spn add "HOST/${NBALIAS^^}" "$(hostname -s)$"
samba-tool spn add "HOST/${NBALIAS,,}.$(hostname -d)" "$(hostname -s)$"

# Add DNS CNAME record for the DC account
samba-tool dns add 127.0.0.1 "$(hostname -d)" "${NBALIAS,,}" CNAME "$(hostname)" -P

exit 0 # Force success
EOF

# Restart required to make NBALIAS work
systemctl --user restart samba-dc.service
