#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import samba

def main():
    config = {
        'credentials_required': os.getenv("SERVER_ROLE") == "member",
        'realm': get_realm_lc(),
        'domain': os.getenv('DOMAIN', get_realm_lc()),
        'nbalias': os.getenv('NBALIAS'),
        'nbdomain': os.getenv('NBDOMAIN'),
        'ipaddress': os.getenv('IPADDRESS'),
        'ipaddress_list': samba.ipaddress_list(skip_wg0=True),
        'hostname': os.getenv('HOSTNAME')
    }
    json.dump(config, fp=sys.stdout)

def get_realm_lc():
    try:
        return os.environ["REALM"].lower()
    except KeyError:
        return None

if __name__ == "__main__":
    main()
